#!/bin/bash

# If we have a .taskenv file load it as source
if [ -f .taskenv ]; then
    source .taskenv
fi

# This makes all bin packages installed via npm available here
# e.g. bogota, nyc, autocannon, etc.
PATH=./node_modules/.bin:$PATH
#This will make all scripts available in the ./src/bin directory
PATH=./src/bin:$PATH

##########################################
# Build
##########################################

function build:release {
    pushd main
    go build -ldflags="-s -w" server.go
    upx -f server
}

##########################################
# Help
##########################################
function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | grep -v '^_' | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-help}  